
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      properties:
        hibernate.hbm2ddl.auto: none
    properties:
      org.hibernate.envers.audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
      org.hibernate.envers.track_entities_changed_in_revision: false
      org.hibernate.envers.audit_strategy_validity_store_revend_timestamp: false
      # allow auditing of field 'version'
      org.hibernate.envers.do_not_audit_optimistic_locking_field: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  mvc:
    log-resolved-exception: false

  flyway:
    enabled: false
  liquibase:
    enabled: true

logging:
  level:
    org.hibernate: INFO


---
spring:
  profiles: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tutorial-envers
    username: root
    password: example

---
spring:
  profiles: sql-log
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: false
